--liquibase formatted sql

--changeset sergey:4
INSERT INTO currency_names (secid, name, shortname) VALUES
('AEDRUBTODTOM', 'Дирхам ОАЭ Своп TOD/TOM', 'AED_TODTOM'),
('AEDRUB_SPT', 'Дирхам ОАЭ SPOT', 'AEDRUB_SPT'),
('AEDRUB_TMS', 'Дирхам ОАЭ (малые лоты) TMS', 'AEDRUB_TMS'),
('AEDRUB_TOD', 'Дирхам ОАЭ TOD', 'AEDRUB_TOD'),
('AEDRUB_TOM', 'Дирхам ОАЭ TOM', 'AEDRUB_TOM'),
('AEDRUB_TOM1D', 'Дирхам ОАЭ Своп TOM/SPT', 'AED_TOMSPT'),
('AMDRUBTODTOM', 'Армянский драм Своп TOD/TOM', 'AMD_TODTOM'),
('AMDRUB_TMS', 'Армянский драм (малые лоты) TMS', 'AMDRUB_TMS'),
('AMDRUB_TOD', 'Армянский драм TOD', 'AMDRUB_TOD'),
('AMDRUB_TOM', 'Армянский драм TOM', 'AMDRUB_TOM'),
('AZNRUBTODTOM', 'Азербайджанский манат Своп TOD/TOM', 'AZN_TODTOM'),
('AZNRUB_TMS', 'Азербайджанский манат (малые лоты) TMS', 'AZNRUB_TMS'),
('AZNRUB_TOD', 'Азербайджанский манат TOD', 'AZNRUB_TOD'),
('AZNRUB_TOM', 'Азербайджанский манат TOM', 'AZNRUB_TOM'),
('BYNRUBTODTOM', 'Белорусский рубль Своп TOD/TOM', 'BYN_TODTOM'),
('BYNRUB_TMS', 'Белорусский рубль (малые лоты) TMS', 'BYNRUB_TMS'),
('BYNRUB_TOD', 'Белорусский рубль TOD', 'BYNRUB_TOD'),
('BYNRUB_TOM', 'Белорусский рубль TOM', 'BYNRUB_TOM'),
('CHFRUBTODTOM', 'Швейцарский франк Своп TOD/TOM', 'CHF_TODTOM'),
('CHFRUB_SPT', 'Швейцарский франк SPOT', 'CHFRUB_SPT'),
('CHFRUB_TMS', 'Швейцарский франк (малые лоты) TMS', 'CHFRUB_TMS'),
('CHFRUB_TOD', 'Швейцарский франк TOD', 'CHFRUB_TOD'),
('CHFRUB_TOM', 'Швейцарский франк TOM', 'CHFRUB_TOM'),
('CHFRUB_TOM1D', 'Швейцарский франк Своп TOM/SPT', 'CHF_TOMSPT'),
('CNY000000TOD', 'Китайский юань TOD', 'CNYRUB_TOD'),
('CNYRUBTODTOM', 'Китайский юань Своп TOD/TOM', 'CNY_TODTOM'),
('CNYRUB_FWD', 'Китайский юань FWD', 'CNYRUB_LTV'),
('CNYRUB_SPT', 'Китайский юань SPOT', 'CNYRUB_SPT'),
('CNYRUB_TMS', 'Китайский юань (малые лоты) TMS', 'CNYRUB_TMS'),
('CNYRUB_TOM', 'Китайский юань TOM', 'CNYRUB_TOM'),
('CNYRUB_TOM1D', 'Китайский юань Своп TOM/SPT', 'CNY_TOMSPT'),
('CNYRUB_TOM1M', 'Китайский юань Своп TOM/1M', 'CNY_TOM1M'),
('CNYRUB_TOM1W', 'Китайский юань Своп TOM/1W', 'CNY_TOM1W'),
('CNYRUB_TOM2M', 'Китайский юань Своп TOM/2M', 'CNY_TOM2M'),
('CNYRUB_TOM2W', 'Китайский юань Своп TOM/2W', 'CNY_TOM2W'),
('CNYRUB_TOM3M', 'Китайский юань Своп TOM/3M', 'CNY_TOM3M'),
('CNYRUB_TOM6M', 'Китайский юань Своп TOM/6M', 'CNY_TOM6M'),
('EUR000TODTOM', 'Евро Своп TOD/TOM', 'EUR_TODTOM'),
('EURRUB_FWD', 'Евро FWD', 'EURRUB_LTV'),
('EURRUB_SPT', 'Евро SPOT', 'EURRUB_SPT'),
('EURRUB_TMS', 'Евро (малые лоты) TMS', 'EURRUB_TMS'),
('EURRUB_TOM1D', 'Евро Своп TOM/SPT', 'EUR_TOMSPT'),
('EURRUB_TOM1M', 'Евро Своп TOM/1M', 'EUR_TOM1M'),
('EURRUB_TOM1W', 'Евро Своп TOM/1W', 'EUR_TOM1W'),
('EURRUB_TOM1Y', 'Евро Своп TOM/1Y', 'EUR_TOM1Y'),
('EURRUB_TOM2M', 'Евро Своп TOM/2M', 'EUR_TOM2M'),
('EURRUB_TOM2W', 'Евро Своп TOM/2W', 'EUR_TOM2W'),
('EURRUB_TOM3M', 'Евро Своп TOM/3M', 'EUR_TOM3M'),
('EURRUB_TOM6M', 'Евро Своп TOM/6M', 'EUR_TOM6M'),
('EURRUB_TOM9M', 'Евро Своп TOM/9M', 'EUR_TOM9M'),
('EURUSD000TOD', 'EUR/USD TOD', 'EURUSD_TOD'),
('EURUSD000TOM', 'EUR/USD TOM', 'EURUSD_TOM'),
('EURUSDTODTOM', 'EUR/USD Своп TOD/TOM', 'EURUSDTDTM'),
('EURUSD_SPT', 'EUR/USD SPOT', 'EURUSD_SPT'),
('EURUSD_TOM1D', 'EUR/USD Своп TOM/SPT', 'EURUSDTMSP'),
('EUR_RUB__TOD', 'Евро TOD', 'EURRUB_TOD'),
('EUR_RUB__TOM', 'Евро TOM', 'EURRUB_TOM'),
('GBPRUBTODTOM', 'Фунт стерлингов Своп TOD/TOM', 'GBP_TODTOM'),
('GBPRUB_SPT', 'Фунт стерлингов SPOT', 'GBPRUB_SPT'),
('GBPRUB_TMS', 'Фунт стерлингов (малые лоты) TMS', 'GBPRUB_TMS'),
('GBPRUB_TOD', 'Фунт стерлингов TOD', 'GBPRUB_TOD'),
('GBPRUB_TOM', 'Фунт стерлингов TOM', 'GBPRUB_TOM'),
('GBPRUB_TOM1D', 'Фунт стерлингов Своп TOM/SPT', 'GBP_TOMSPT'),
('GBPUSDTODTOM', 'GBP/USD Своп TOD/TOM', 'GBPUSDTDTM'),
('GBPUSD_SPT', 'GBP/USD SPOT', 'GBPUSD_SPT'),
('GBPUSD_TOD', 'GBP/USD TOD', 'GBPUSD_TOD'),
('GBPUSD_TOM', 'GBP/USD TOM', 'GBPUSD_TOM'),
('GBPUSD_TOM1D', 'GBP/USD Своп TOM/SPT', 'GBPUSDTMSP'),
('GLDRUBTODTOM', 'Золото Своп TOD/TOM', 'GLD_TODTOM'),
('GLDRUB_FWD', 'Золото FWD', 'GLDRUB_LTV'),
('GLDRUB_SPT', 'Золото SPOT', 'GLDRUB_SPT'),
('GLDRUB_TOD', 'Золото TOD', 'GLDRUB_TOD'),
('GLDRUB_TOM', 'Золото TOM', 'GLDRUB_TOM'),
('GLDRUB_TOM1D', 'Золото Своп TOM/SPT', 'GLD_TOMSPT'),
('GLDRUB_TOM1M', 'Золото Своп TOM/1M', 'GLD_TOM1M'),
('GLDRUB_TOM1W', 'Золото Своп TOM/1W', 'GLD_TOM1W'),
('GLDRUB_TOM6M', 'Золото Своп TOM/6M', 'GLD_TOM6M'),
('HKDRUBTODTOM', 'Гонконгский доллар Своп TOD/TOM', 'HKD_TODTOM'),
('HKDRUB_TMS', 'Гонконгский доллар (малые лоты) TMS', 'HKDRUB_TMS'),
('HKDRUB_TOD', 'Гонконгский доллар TOD', 'HKDRUB_TOD'),
('HKDRUB_TOM', 'Гонконгский доллар TOM', 'HKDRUB_TOM'),
('JPYRUBTODTOM', 'Японская йена Своп TOD/TOM', 'JPY_TODTOM'),
('JPYRUB_SPT', 'Японская йена SPOT', 'JPYRUB_SPT'),
('JPYRUB_TMS', 'Японская йена (малые лоты) TMS', 'JPYRUB_TMS'),
('JPYRUB_TOD', 'Японская йена TOD', 'JPYRUB_TOD'),
('JPYRUB_TOM', 'Японская йена TOM', 'JPYRUB_TOM'),
('JPYRUB_TOM1D', 'Японская йена Своп TOM/SPT', 'JPY_TOMSPT'),
('KGSRUBTODTOM', 'Киргизский сом TOM', 'KGS_TODTOM'),
('KGSRUB_TOD', 'Киргизский сом TOD', 'KGSRUB_TOD'),
('KGSRUB_TOM', 'Киргизский сом TOM', 'KGSRUB_TOM'),
('KZTRUBTODTOM', 'Казахстанский тенге Своп TOD/TOM', 'KZT_TODTOM'),
('KZTRUB_FWD', 'Казахстанский тенге FWD', 'KZTRUB_LTV'),
('KZTRUB_SPT', 'Казахстанский тенге SPOT', 'KZTRUB_SPT'),
('KZTRUB_TMS', 'Казахстанский тенге (малые лоты) TMS', 'KZTRUB_TMS'),
('KZTRUB_TOD', 'Казахстанский тенге TOD', 'KZTRUB_TOD'),
('KZTRUB_TOM', 'Казахстанский тенге TOM', 'KZTRUB_TOM'),
('KZTRUB_TOM1D', 'Казахстанский тенге Своп TOM/SPT', 'KZT_TOMSPT'),
('KZTRUB_TOM1M', 'Казахстанский тенге Своп TOM/1M', 'KZT_TOM1M'),
('KZTRUB_TOM1W', 'Казахстанский тенге Своп TOM/1W', 'KZT_TOM1W'),
('KZTRUB_TOM2M', 'Казахстанский тенге Своп TOM/2M', 'KZT_TOM2M'),
('KZTRUB_TOM2W', 'Казахстанский тенге Своп TOM/2W', 'KZT_TOM2W'),
('KZTRUB_TOM3M', 'Казахстанский тенге Своп TOM/3M', 'KZT_TOM3M'),
('KZTRUB_TOM6M', 'Казахстанский тенге Своп TOM/6M', 'KZT_TOM6M'),
('PLDRUBTODTOM', 'Палладий Своп TOD/TOM', 'PLD_TODTOM'),
('PLDRUB_FWD', 'Палладий FWD', 'PLDRUB_LTV'),
('PLDRUB_SPT', 'Палладий SPOT', 'PLDRUB_SPT'),
('PLDRUB_TOD', 'Палладий TOD', 'PLDRUB_TOD'),
('PLDRUB_TOM', 'Палладий TOM', 'PLDRUB_TOM'),
('PLDRUB_TOM1D', 'Палладий Своп TOM/SPT', 'PLD_TOMSPT'),
('PLDRUB_TOM1M', 'Палладий Своп TOM/1M', 'PLD_TOM1M'),
('PLDRUB_TOM1W', 'Палладий Своп TOM/1W', 'PLD_TOM1W'),
('PLDRUB_TOM6M', 'Палладий Своп TOM/6M', 'PLD_TOM6M'),
('PLTRUBTODTOM', 'Платина Своп TOD/TOM', 'PLT_TODTOM'),
('PLTRUB_FWD', 'Платина FWD', 'PLTRUB_LTV'),
('PLTRUB_SPT', 'Платина SPOT', 'PLTRUB_SPT'),
('PLTRUB_TOD', 'Платина TOD', 'PLTRUB_TOD'),
('PLTRUB_TOM', 'Платина TOM', 'PLTRUB_TOM'),
('PLTRUB_TOM1D', 'Платина Своп TOM/SPT', 'PLT_TOMSPT'),
('PLTRUB_TOM1M', 'Платина Своп TOM/1M', 'PLT_TOM1M'),
('PLTRUB_TOM1W', 'Платина Своп TOM/1W', 'PLT_TOM1W'),
('PLTRUB_TOM6M', 'Платина Своп TOM/6M', 'PLT_TOM6M'),
('SLVRUBTODTOM', 'Серебро Своп TOD/TOM', 'SLV_TODTOM'),
('SLVRUB_FWD', 'Серебро FWD', 'SLVRUB_LTV'),
('SLVRUB_SPT', 'Серебро SPOT', 'SLVRUB_SPT'),
('SLVRUB_TOD', 'Серебро TOD', 'SLVRUB_TOD'),
('SLVRUB_TOM', 'Серебро TOM', 'SLVRUB_TOM'),
('SLVRUB_TOM1D', 'Серебро Своп TOM/SPT', 'SLV_TOMSPT'),
('SLVRUB_TOM1M', 'Серебро Своп TOM/1M', 'SLV_TOM1M'),
('SLVRUB_TOM1W', 'Серебро Своп TOM/1W', 'SLV_TOM1W'),
('SLVRUB_TOM6M', 'Серебро Своп TOM/6M', 'SLV_TOM6M'),
('TJSRUBTODTOM', 'Таджикский сомони TOM', 'TJS_TODTOM'),
('TJSRUB_TOD', 'Таджикский сомони TOD', 'TJSRUB_TOD'),
('TJSRUB_TOM', 'Таджикский сомони TOM', 'TJSRUB_TOM'),
('TRYRUBTODTOM', 'Турецкая лира TOM', 'TRY_TODTOM'),
('TRYRUB_TMS', 'Турецкая лира (малые лоты) TMS', 'TRYRUB_TMS'),
('TRYRUB_TOD', 'Турецкая лира TOD', 'TRYRUB_TOD'),
('TRYRUB_TOM', 'Турецкая лира TOM', 'TRYRUB_TOM'),
('UAH000000TOM', 'Украинская гривна TOD', 'UAHRUB_TOD'),
('USD000000TOD', 'Доллар США TOD', 'USDRUB_TOD'),
('USD000TODTOM', 'Доллар США TOM', 'USD_TODTOM'),
('USD000UTSTOM', 'Доллар США TOM', 'USDRUB_TOM'),
('USDAEDTODTOM', 'Доллар/Дирхам Своп TOD/TOM', 'USDAEDTDTM'),
('USDAED_SPT', 'Доллар/Дирхам SPOT', 'USDAED_SPT'),
('USDAED_TOD', 'Доллар/Дирхам TOD', 'USDAED_TOD'),
('USDAED_TOM', 'Доллар/Дирхам TOM', 'USDAED_TOM'),
('USDAED_TOM1D', 'Доллар/Дирхам Своп TOM/SPT', 'USDAEDTMSP'),
('USDAMDTODTOM', 'Армянский драм Своп TOD/TOM', 'USDAMDTDTM'),
('USDAMD_TOD', 'Армянский драм TOD', 'USDAMD_TOD'),
('USDAMD_TOM', 'Армянский драм TOM', 'USDAMD_TOM'),
('USDAZNTODTOM', 'Азербайджанский манат Своп TOD/TOM', 'USDAZNTDTM'),
('USDAZN_TOD', 'Азербайджанский манат TOD', 'USDAZN_TOD'),
('USDAZN_TOM', 'Азербайджанский манат TOM', 'USDAZN_TOM'),
('USDCHFTODTOM', 'Швейцарский франк Своп TOD/TOM', 'USDCHFTDTM'),
('USDCHF_SPT', 'Швейцарский франк SPOT', 'USDCHF_SPT'),
('USDCHF_TOD', 'Швейцарский франк TOD', 'USDCHF_TOD'),
('USDCHF_TOM', 'Швейцарский франк TOM', 'USDCHF_TOM'),
('USDCHF_TOM1D', 'Швейцарский франк Своп TOM/SPT', 'USDCHFTMSP'),
('USDCNYTODTOM', 'Доллар/Юань Своп TOD/TOM', 'USDCNYTDTM'),
('USDCNY_SPT', 'Доллар/Юань SPOT', 'USDCNY_SPT'),
('USDCNY_TOD', 'Доллар/Юань TOD', 'USDCNY_TOD'),
('USDCNY_TOM', 'Доллар/Юань TOM', 'USDCNY_TOM'),
('USDCNY_TOM1D', 'Доллар/Юань Своп TOM/SPT', 'USDCNYTMSP'),
('USDJPYTODTOM', 'Доллар/Йена Своп TOD/TOM', 'USDJPYTDTM'),
('USDJPY_SPT', 'Доллар/Йена SPOT', 'USDJPY_SPT'),
('USDJPY_TOD', 'Доллар/Йена TOD', 'USDJPY_TOD'),
('USDJPY_TOM', 'Доллар/Йена TOM', 'USDJPY_TOM'),
('USDJPY_TOM1D', 'Доллар/Йена Своп TOM/SPT', 'USDJPYTMSP'),
('USDKZTTODTOM', 'Доллар/Тенге Своп TOD/TOM', 'USDKZTTDTM'),
('USDKZT_SPT', 'Доллар/Тенге SPOT', 'USDKZT_SPT'),
('USDKZT_TOD', 'Доллар/Тенге TOD', 'USDKZT_TOD'),
('USDKZT_TOM', 'Доллар/Тенге TOM', 'USDKZT_TOM'),
('USDKZT_TOM1D', 'Доллар/Тенге Своп TOM/SPT', 'USDKZTTMSP'),
('USDRUB_DIS', 'Доллар США Аукцион', 'USDRUB_DIS'),
('USDRUB_SPT', 'Доллар США SPOT', 'USDRUB_SPT'),
('USDRUB_TMS', 'Доллар США (малые лоты) TMS', 'USDRUB_TMS'),
('USDRUB_TOM1D', 'Доллар США SPOT', 'USD_TOMSPT'),
('USDRUB_TOM1M', 'Доллар США Своп TOM/1M', 'USD_TOM1M'),
('USDRUB_TOM1W', 'Доллар США Своп TOM/1W', 'USD_TOM1W'),
('USDRUB_TOM1Y', 'Доллар США Своп TOM/1Y', 'USD_TOM1Y'),
('USDRUB_TOM2M', 'Доллар США Своп TOM/2M', 'USD_TOM2M'),
('USDRUB_TOM2W', 'Доллар США Своп TOM/2W', 'USD_TOM2W'),
('USDRUB_TOM3M', 'Доллар США Своп TOM/3M', 'USD_TOM3M'),
('USDRUB_TOM6M', 'Доллар США Своп TOM/6M', 'USD_TOM6M'),
('USDRUB_TOM9M', 'Доллар США Своп TOM/9M', 'USD_TOM9M'),
('USDTRYTODTOM', 'Доллар/Лира Своп TOD/TOM', 'USDTRYTDTM'),
('USDTRY_SPT', 'Доллар/Лира SPOT', 'USDTRY_SPT'),
('USDTRY_TOD', 'Доллар/Лира TOD', 'USDTRY_TOD'),
('USDTRY_TOM', 'Доллар/Лира TOM', 'USDTRY_TOM'),
('USDTRY_TOM1D', 'Доллар/Лира Своп TOM/SPT', 'USDTRYTMSP'),
('USDZARTODTOM', 'Доллар США Своп TOD/TOM', 'USDZARTDTM'),
('USDZAR_TOD', 'Доллар США TOD', 'USDZAR_TOD'),
('USDZAR_TOM', 'Доллар США TOM', 'USDZAR_TOM'),
('UZSRUBTODTOM', 'Узбекский сум TOM', 'UZS_TODTOM'),
('UZSRUB_TOD', 'Узбекский сум TOD', 'UZSRUB_TOD'),
('UZSRUB_TOM', 'Узбекский сум TOM', 'UZSRUB_TOM'),
('ZARRUBTODTOM', 'Южноафриканский рэнд TOM', 'ZAR_TODTOM'),
('ZARRUB_TMS', 'Южноафриканский рэнд (малые лоты) TMS', 'ZARRUB_TMS'),
('ZARRUB_TOD', 'Южноафриканский рэнд TOD', 'ZARRUB_TOD'),
('ZARRUB_TOM', 'Южноафриканский рэнд TOM', 'ZARRUB_TOM');
