--liquibase formatted sql

--changeset sergey:8
ALTER TABLE users
ADD COLUMN IF NOT EXISTS first_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS last_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS avatar VARCHAR(255);
--rollback ALTER TABLE users DROP COLUMN first_name, DROP COLUMN last_name, DROP COLUMN phone, DROP COLUMN country, DROP COLUMN city, DROP COLUMN avatar;
